export default [
  { name: "Bitcoin", symbol: "BTC", tradingview: "CRYPTOCAP:BTC" },
  { name: "Ethereum", symbol: "ETH", tradingview: "CRYPTOCAP:ETH" },
  { name: "XRP", symbol: "XRP", tradingview: "CRYPTOCAP:LTC" },
  { name: "Litecoin", symbol: "LTC", tradingview: "CRYPTOCAP:LTC" },
  { name: "Bitcoin Cash", symbol: "BCH", tradingview: "CRYPTOCAP:BCH" },
  { name: "Binance Coin", symbol: "BNB", tradingview: "CRYPTOCAP:BNB" },
  { name: "EOS", symbol: "EOS", tradingview: "CRYPTOCAP:EOS" },
  { name: "Tether", symbol: "USDT", tradingview: "CRYPTOCAP:USDT" },
  { name: "Bitcoin SV", symbol: "BSV", tradingview: "CRYPTOCAP:BSV" },
  { name: "Stellar", symbol: "XLM", tradingview: "CRYPTOCAP:XLM" },
  { name: "TRON", symbol: "TRX", tradingview: "CRYPTOCAP:TRX" },
  { name: "Cardano", symbol: "ADA", tradingview: "CRYPTOCAP:ADA" },
  { name: "Monero", symbol: "XMR", tradingview: "CRYPTOCAP:XMR" },
  { name: "UNUS SED LEO", symbol: "LEO", tradingview: "NYSE:LEO" },
  { name: "Dash", symbol: "DASH", tradingview: "TSXV:DASH" },
  { name: "Chainlink", symbol: "LINK", tradingview: "BIST:LINK" },
  { name: "IOTA", symbol: "MIOTA", tradingview: "CRYPTOCAP:MIOTA" },
  { name: "NEO", symbol: "NEO", tradingview: "NASDAQ:NEO" },
  { name: "Cosmos", symbol: "ATOM", tradingview: "NASDAQ:ATOM" }
]
