# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.16.3

pipelines:
  develop:
    - step:
        name: Install, Lint, Tests and Build
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - echo "npm install"
          - npm install
          - echo "npm run lint"
          - echo "Nothing setup here" #- npm run lint
          - echo "npm run test"
          - npm run test
          - echo "npm run build"
          - npm run build
    - step:
        name: Deploy to test
        caches:
          - node
        trigger: manual
        deployment: Test
        script:
          - npm run build
          - npm run deploy:test
  staging:
    - step:
        name: Install, Lint, Tests and Build
        caches:
          - node-staging
        script: # Modify the commands below to build your repository.
          - echo "npm install"
          - npm install
          - echo "npm run lint"
          - echo "Nothing setup here" #- npm run lint
          - echo "npm run test"
          - npm run test
          - echo "npm run build"
          - npm run build
    - step:
        name: Deploy to staging
        deployment: Staging
        # cache:
        #   - node-staging
        script:
          - echo "Nothing setup here"
  production:
    - step:
        name: Install, Lint, Tests and Build
        caches:
          - node-production
    - step:
        name: Deploy to production
        caches:
          - node-production
        deployment: Production
        trigger: manual
        script:
          - npm i -g pm2
          - echo "pm2 deploy production"
          - pm2 deploy production
